name: Learn GA

on: [workflow_dispatch, push]

jobs:
  some_command:
    name: Run Sth
    runs-on: windows-2019
    steps:
      - name: run sth 1
        shell: pwsh
        run: | 
          echo "Hello, world!"
          
          echo "uname"
          uname -a
          
          echo "Current Working Dir:"
          pwd
          
          echo "Print path to pwsh.exe"
          which pwsh
          
      - uses: actions/checkout@v2
      - name: run sth 2
        shell: pwsh
        run: |
          echo "ls:"
          ls
