name: Learn GA

on: workflow_dispatch

jobs:
  some_command:
    name: Run Sth
    runs-on: windows-latest
    steps:
      - name: pwd
        shell: pwsh
        run: | 
          echo "Hello, world!"
          echo "uname"
          uname
          echo "Current Working Dir:"
          pwd

